# Generated by Django 4.1.4 on 2022-12-31 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=264)),
                ('album_cover', models.ImageField(default='player/images/album_default_cover.png', upload_to='player/images')),
                ('public_day', models.DateField()),
            ],
            options={
                'ordering': ['-public_day'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=264)),
                ('albums', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=20)),
                ('avartar', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=264)),
                ('audio', models.ImageField(default='player/audio/dummy-audio.mp3', upload_to='player/audio')),
                ('song_cover', models.ImageField(default='player/images/song_default_cover.png', upload_to='player/images')),
                ('public_day', models.DateField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='player.album')),
                ('artists', models.ManyToManyField(to='player.artist')),
            ],
            options={
                'ordering': ['-public_day'],
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='songs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='player.song'),
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(to='player.artist'),
        ),
    ]
