# Generated by Django 4.1.4 on 2023-01-02 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='albums',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_cover',
        ),
        migrations.RemoveField(
            model_name='album',
            name='artists',
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='player.artist'),
        ),
    ]
