# Generated by Django 4.1.4 on 2023-01-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_remove_artist_albums_remove_artist_songs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
        migrations.RemoveField(
            model_name='song',
            name='public_day',
        ),
    ]
