# Generated by Django 4.1.2 on 2023-01-05 22:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_alter_song_options_remove_song_public_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='event',
        ),
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(default='player/image/default.png', upload_to='player/images'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='avartar',
            field=models.ImageField(default='player/image/default.png', upload_to='player/images'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=500)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(default='player/image/default.png', upload_to='player/images')),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('artists', models.ManyToManyField(to='player.artist')),
            ],
        ),
    ]
