# Generated by Django 4.1.2 on 2023-01-07 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_remove_artist_event_alter_album_album_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artists',
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='player.artist'),
        ),
    ]
