# Generated by Django 4.1.2 on 2023-01-07 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_remove_song_artists_song_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='public_day',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
