# Generated by Django 4.1.2 on 2023-01-07 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_alter_album_public_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='public_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
