# Generated by Django 4.1.2 on 2023-01-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_alter_album_public_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='public_day',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
