# Generated by Django 4.1.4 on 2023-01-08 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_alter_album_public_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='public_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
