# Generated by Django 4.1.4 on 2023-01-08 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_alter_album_public_day_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='artists',
        ),
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='player.artist'),
        ),
    ]
