# Generated by Django 4.1.4 on 2023-01-08 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_remove_event_artists_event_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='artists',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='player.artist'),
        ),
    ]
