# Generated by Django 4.1.4 on 2023-01-01 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0002_listenerprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listener',
            name='playlist',
        ),
    ]
